export const shopActionTypes = {
    GET_COLLECTION: 'GET_COLLECTION',
    UPDATE_COLLECTION: 'UPDATE_COLLECTION',
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE'
};